// Demo/seed data — 5-8 sample items per resource so the site isn't empty
// on first run. Safe to edit or delete once you have real content.

const skills = [
  { name: "React.js", category: "Frontend", percentage: 92 },
  { name: "JavaScript (ES6+)", category: "Frontend", percentage: 90 },
  { name: "HTML5 & CSS3", category: "Frontend", percentage: 95 },
  { name: "Node.js", category: "Backend", percentage: 88 },
  { name: "Express.js", category: "Backend", percentage: 87 },
  { name: "MongoDB", category: "Database", percentage: 85 },
  { name: "Mongoose", category: "Database", percentage: 84 },
  { name: "Git & GitHub", category: "Tools", percentage: 90 },
  { name: "REST API Design", category: "Backend", percentage: 89 },
  { name: "Socket.IO", category: "Other", percentage: 80 },
];

const services = [
  {
    title: "MERN Web Development",
    description: "End-to-end web applications built with MongoDB, Express, React and Node.js — from database design to deployment.",
    startingPrice: "$500",
    order: 1,
  },
  {
    title: "React Frontend Development",
    description: "Fast, responsive, component-driven interfaces with clean state management and pixel-perfect design.",
    startingPrice: "$300",
    order: 2,
  },
  {
    title: "REST API Development",
    description: "Secure, well-documented REST APIs with authentication, validation and role-based access control.",
    startingPrice: "$250",
    order: 3,
  },
  {
    title: "Admin Dashboard Development",
    description: "Custom admin panels with analytics, CRUD management, and real-time notifications for your platform.",
    startingPrice: "$400",
    order: 4,
  },
  {
    title: "Authentication & Authorization",
    description: "JWT-based auth systems, role management, and secure password handling for web and mobile apps.",
    startingPrice: "$150",
    order: 5,
  },
  {
    title: "Website Maintenance & Support",
    description: "Ongoing bug fixes, performance improvements, and feature updates for existing MERN applications.",
    startingPrice: "$99/mo",
    order: 6,
  },
];

const experience = [
  {
    type: "Education",
    title: "Bachelor's in Computer Science",
    organization: "University",
    location: "Pakistan",
    startDate: new Date("2020-09-01"),
    endDate: new Date("2024-06-30"),
    isCurrent: false,
    description: "Studied core computer science fundamentals — data structures, algorithms, databases and web technologies.",
    order: 1,
  },
  {
    type: "Training",
    title: "MERN Stack Development Bootcamp",
    organization: "Online Training Program",
    location: "Remote",
    startDate: new Date("2023-01-01"),
    endDate: new Date("2023-06-30"),
    isCurrent: false,
    description: "Intensive hands-on training covering MongoDB, Express, React, Node.js and full-stack project deployment.",
    order: 2,
  },
  {
    type: "Freelance",
    title: "Freelance MERN Stack Developer",
    organization: "Self-employed",
    location: "Remote",
    startDate: new Date("2023-07-01"),
    isCurrent: true,
    description: "Building full-stack web applications, REST APIs and admin dashboards for clients worldwide.",
    order: 3,
  },
  {
    type: "Project",
    title: "E-commerce Platform",
    organization: "Client Project",
    location: "Remote",
    startDate: new Date("2023-09-01"),
    endDate: new Date("2023-12-01"),
    isCurrent: false,
    description: "Built a full e-commerce platform with product management, cart, checkout and an admin dashboard.",
    order: 4,
  },
  {
    type: "Job",
    title: "Junior Web Developer",
    organization: "Local Software House",
    location: "Karachi, Pakistan",
    startDate: new Date("2024-07-01"),
    isCurrent: true,
    description: "Working on client web applications using React and Node.js, collaborating with a small dev team.",
    order: 5,
  },
];

const testimonials = [
  {
    clientName: "Ahmed Raza",
    position: "Founder",
    company: "StartupHub",
    rating: 5,
    review: "Qamar delivered our MVP ahead of schedule and the code quality was excellent. Highly recommended for any MERN project.",
  },
  {
    clientName: "Sara Khan",
    position: "Product Manager",
    company: "TechNova",
    rating: 5,
    review: "Great communication throughout the project. He understood our requirements quickly and built exactly what we needed.",
  },
  {
    clientName: "Usman Ali",
    position: "CEO",
    company: "Bright Solutions",
    rating: 4,
    review: "Solid backend architecture and clean API design. Would definitely work with him again on future projects.",
  },
  {
    clientName: "Emily Johnson",
    position: "Marketing Director",
    company: "GrowthLab",
    rating: 5,
    review: "Our new dashboard is fast, intuitive and exactly on-brand. Qamar was responsive and easy to work with.",
  },
  {
    clientName: "Bilal Ahmed",
    position: "CTO",
    company: "DevWorks",
    rating: 5,
    review: "Impressive attention to detail and strong problem-solving skills. The real-time chat feature works flawlessly.",
  },
  {
    clientName: "Fatima Malik",
    position: "Operations Lead",
    company: "RetailPro",
    rating: 4,
    review: "Professional, punctual, and delivered a scalable admin panel that our team uses daily.",
  },
];

const projects = [
  {
    title: "E-Commerce Platform",
    slug: "ecommerce-platform",
    description: "A full-featured e-commerce platform with product catalog, cart, checkout, order tracking and an admin dashboard for inventory management.",
    shortDescription: "Full-featured online store with admin inventory management.",
    thumbnail: "",
    technologies: ["React", "Node.js", "Express", "MongoDB", "Stripe"],
    category: "Full Stack",
    liveUrl: "",
    githubUrl: "",
    featured: true,
    status: "Completed",
    order: 1,
  },
  {
    title: "Real Estate Listing App",
    slug: "real-estate-listing-app",
    description: "A property listing platform with search filters, map integration, saved listings and an agent dashboard for managing property posts.",
    shortDescription: "Property listing platform with search and map integration.",
    technologies: ["React", "Node.js", "Express", "MongoDB", "Mapbox"],
    category: "MERN",
    featured: true,
    status: "Completed",
    order: 2,
  },
  {
    title: "Freelance Client Portal",
    slug: "freelance-client-portal",
    description: "A client management platform with project requests, real-time chat, invoicing and a full admin dashboard — similar in spirit to this very portfolio site.",
    shortDescription: "Client management platform with real-time chat and invoicing.",
    technologies: ["React", "Socket.IO", "Node.js", "Express", "MongoDB"],
    category: "Full Stack",
    featured: true,
    status: "Completed",
    order: 3,
  },
  {
    title: "Task Management API",
    slug: "task-management-api",
    description: "A REST API for a task management tool supporting boards, lists, cards, labels and team collaboration with role-based access control.",
    shortDescription: "REST API for a Trello-like task management tool.",
    technologies: ["Node.js", "Express", "MongoDB", "JWT"],
    category: "API",
    featured: false,
    status: "Completed",
    order: 4,
  },
  {
    title: "Blog & CMS Platform",
    slug: "blog-cms-platform",
    description: "A custom content management system for a blog with rich-text editing, categories, tags, and an analytics dashboard for post views.",
    shortDescription: "Custom CMS with rich-text editing and analytics.",
    technologies: ["React", "Node.js", "Express", "MongoDB"],
    category: "MERN",
    featured: false,
    status: "Completed",
    order: 5,
  },
  {
    title: "Fitness Tracker Dashboard",
    slug: "fitness-tracker-dashboard",
    description: "A personal fitness tracking dashboard with workout logging, progress charts, and goal setting, built as a learning/portfolio project.",
    shortDescription: "Personal fitness tracker with charts and goal tracking.",
    technologies: ["React", "Chart.js", "Node.js", "MongoDB"],
    category: "Frontend",
    featured: false,
    status: "In Progress",
    order: 6,
  },
];

const blogs = [
  {
    title: "Why I Chose the MERN Stack for Freelance Projects",
    slug: "why-i-chose-mern-stack",
    excerpt: "A look at why MongoDB, Express, React and Node.js form such a productive stack for freelance client work.",
    content: "The MERN stack lets me move fast without sacrificing scalability. Using a single language (JavaScript) across the frontend and backend cuts down context-switching, and the ecosystem around React and Express means most common problems already have a well-tested solution.\n\nFor client projects specifically, this means faster delivery timelines and easier long-term maintenance — both for me and for whoever inherits the codebase later.",
    category: "Web Development",
    tags: ["MERN", "JavaScript", "Freelancing"],
    featured: true,
    published: true,
  },
  {
    title: "Structuring a Scalable Express.js Backend",
    slug: "structuring-scalable-express-backend",
    excerpt: "A practical guide to organizing controllers, routes, models and middleware in a growing Express API.",
    content: "As an Express API grows, keeping routes, controllers and models cleanly separated pays off enormously. I typically split my backend into config, models, controllers, routes, middleware and services folders — each with a single responsibility.\n\nThis structure makes it trivial to onboard new developers, write tests, and reason about where a given piece of logic belongs.",
    category: "Backend",
    tags: ["Express", "Node.js", "Architecture"],
    featured: true,
    published: true,
  },
  {
    title: "Building Real-Time Chat with Socket.IO",
    slug: "building-realtime-chat-with-socketio",
    excerpt: "How I added a real-time client chat system to a MERN admin dashboard using Socket.IO.",
    content: "Socket.IO makes real-time features approachable even for developers new to WebSockets. For a client-facing chat widget, the key pieces are: authenticating the socket connection with a JWT, joining per-conversation rooms, and persisting every message to MongoDB so history survives reconnects.\n\nI also broadcast unread counts to an 'admin-room' so the dashboard can show live notification badges.",
    category: "Real-Time",
    tags: ["Socket.IO", "Chat", "MERN"],
    featured: false,
    published: true,
  },
  {
    title: "JWT Authentication Best Practices in Node.js",
    slug: "jwt-authentication-best-practices",
    excerpt: "Common pitfalls and best practices when implementing JWT-based authentication in a Node/Express API.",
    content: "JWTs are simple to implement but easy to get subtly wrong. A few practices I follow: short expiry windows with refresh flows for sensitive apps, always hashing passwords with bcrypt before storage, and never storing secrets or tokens in frontend code or version control.\n\nRole-based middleware (like an isAdmin guard) should always run after token verification, never before.",
    category: "Security",
    tags: ["JWT", "Security", "Node.js"],
    featured: false,
    published: true,
  },
  {
    title: "Designing a Clean React Component Folder Structure",
    slug: "clean-react-component-folder-structure",
    excerpt: "My approach to organizing components, pages and shared logic in medium-to-large React applications.",
    content: "I organize React projects around three top-level folders: components (reusable UI pieces, each in its own folder with its CSS), pages (route-level views), and a shared layer of context, hooks, services and utils.\n\nThis keeps components easy to find and test in isolation, while page-level files stay focused on composing those components rather than containing business logic themselves.",
    category: "Frontend",
    tags: ["React", "Architecture", "Best Practices"],
    featured: false,
    published: true,
  },
  {
    title: "From Freelancer to Full Platform: Building My Own Client Portal",
    slug: "building-my-own-client-portal",
    excerpt: "Why I built a full project-request and chat system into my own portfolio instead of just a static site.",
    content: "A static portfolio tells clients what I've built. A platform with project requests, real-time chat and status tracking shows them what it's like to actually work with me.\n\nIt also doubles as a live demo of my MERN stack skills — the site itself is proof of the kind of work I can deliver.",
    category: "Career",
    tags: ["Portfolio", "Freelancing", "MERN"],
    featured: false,
    published: true,
  },
];

module.exports = { skills, services, experience, testimonials, projects, blogs };
